all:
	${MAKE} -C display 		CFLAGS="${CFLAGS}" GL_LIBS="${GL_LIBS}"
	${MAKE} -C plane			CFLAGS="${CFLAGS}" GL_LIBS="${GL_LIBS}"
	${MAKE} -C staticmodel	CFLAGS="${CFLAGS}" GL_LIBS="${GL_LIBS}"

clean:
	${MAKE} -C display		clean
	${MAKE} -C plane			clean
	${MAKE} -C staticmodel 	clean
